[Display_01] Create JUnit5ExampleTest.java
andrewdimmer/csi-3370-software-project-config-test pull request #44
Opened 2020-11-03 03:03 UTC by John-A11

Working on First Test Class JUnit - Test class and code.

2020-11-03 03:50 UTC, andrewdimmer requested changes
Hi John! Can you really quickly make sure you add appropriate labels, projects, and milestones in the right side bar, and the correct issue links in the description? This will help keep the Sprint Task Status Board up to date and searchable. Thank you!

2020-11-03 21:36 UTC, andrewdimmer reviewed
Looks good to me! Feel free to merge once Steve approves!

2020-11-03 21:36 UTC, andrewdimmer approved these changes

2020-11-05 04:18 UTC, stevecatherman approved these changes
Looks lovely.

2020-11-05 04:51 UTC, merged